# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55796899cfa44a12b0045c807d0a84c0b579e79a2ca3ef79161b7abba95fd1c3790dceffc4ce9cd57bfa92ba7ed76866259a3ed00d861f4b7c98b7ddaaa6ca06

test:
  secret_key_base: ce994b9f215037d8d7bf2904a5e34fb0a018b1c87440341c47cc7471a901acf75c6d91a899a165cd444b8e296c9bbbbcf41b39c5c2484dad27be84922fac470c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
